Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/OrderedDependencies:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 100

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
